name: media_kit_native_event_loop
description: Platform specific threaded event handling for media_kit. Enables support for higher number of concurrent instances.
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 1.0.6
funding:
  - https://www.github.com/sponsors/alexmercerind

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true

      # NOTE: package:media_kit ships pre-built package:media_kit_native_event_loop shared libraries on Android within package:media_kit_libs_android_audio & package:media_kit_libs_android_video packages along side libmpv/FFmpeg shared libraries.
      # We do not build on dependent's machine because it requires setting up NDK etc. & build process is rather complex.
      #
      # For building a `libmedia_kit_native_event_loop.so` using this CMake:
      # 1. Generate the plugin_ffi template project for Android using:
      # * flutter create --org com.alexmercerind --template plugin_ffi --platforms=android .
      # 2. Add the libmpv/FFmpeg & other dependencies to which this target will link at:
      # * ../android/libs/lib/arm64-v8a/*
      # * ../android/libs/lib/armeabi-v7a/*
      # * ../android/libs/lib/x86_64/*
      # * ../android/libs/lib/x66/*
      # 3. Add the libmpv headers at include/*
      # 4. Generate the APK file:
      # * flutter build apk --release
      # 5. Extract the `libmedia_kit_native_event_loop.so` for each ABI & architecture.
